// Client action types
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';
export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

// Spare Parts
export const FETCH_SPARE_PARTS = 'FETCH_SPARE_PARTS';
export const CREATE_SPARE_PART = 'CREATE_SPARE_PART';
export const UPDATE_SPARE_PART = 'UPDATE_SPARE_PART';
export const DELETE_SPARE_PART = 'DELETE_SPARE_PART'; 